#!/bin/bash
module load parallel
export LD_LIBRARY_PATH=/global/cscratch1/sd/alexpo7/media/sf_das_compression/include/hdf5/lib
export HDF5_USE_FILE_LOCKING=FALSE
DIRECTORY="/global/project/projectdirs/m1248/Bin_compression_data/Fairbanks_aug16_h5/*"
printf "file_name,cmp_ratio,abs_mean_uncmp,min_uncmp,max_uncmp,mean_uncmp,cmp_time,\n" | tee -a ../logs/output_log_fastpfor.csv
ls $DIRECTORY | parallel ./DAS_Compress {} /global/cscratch1/sd/alexpo7/media/sf_das_compression/data/output/ -d | tee -a ../logs/output_log_fastpfor.csv
